<a href="https://colab.research.google.com/github/hector1994/churn_model_v1/blob/master/SPRINT_7_TT_DA_97_Let's_get_better.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📤 __IMPORTS PRINCIPALES Y CONFIGURACIONES GLOBALES__⚙️
---

In [2]:
#IMPORTS PRINCIPALES:
import pandas  as pd               #LECTURA, MANEJO Y TRANSFORMACIÓN DE DATAFRAMES.
import numpy   as np               #FUNCIONES MATEMÁTICAS RELEVANTES.
import matplotlib.pyplot as plt    #GRÁFICOS.
import seaborn as sns              #GRÁFICOS PRETTY.


#CONFIGURACIONES GLOBALES:
import warnings                                                #MANEJO DE WARNINGS - ADVERTENCIAS
warnings.simplefilter(action='ignore', category=FutureWarning) #QUITAR WARNINGS MOLESTOS
pd.set_option('display.max_columns', None)                     #ELIMINA LIMITES DE PANDAS PARA MOSTRAR COLUMNAS
pd.set_option('display.max_rows', None)                        #ELIMINA LIMITES DE PANDAS PARA MOSTRAR FILAS
pd.set_option('display.max_colwidth', None)                    #AUTOAJUSTA ANCHO DE COLUMNAS

## 🗂️__LEYENDO DATA  + GENERAR PANDAS DATAFRAME__📊
---

In [3]:
#CARGANDO DATA: ESTE DATASET SE ECUENTRA ALMACENADO EN REPOSITORIO DE GITHUB.
ruta_tabla = "https://media.githubusercontent.com/media/hector1994/e_commerce_funnel_data_generator/refs/heads/master/sales_data_dirty_sp7_data.csv"

df_raw     = pd.read_csv(ruta_tabla)  #DATA SIN PROCESAR.
df_raw.head(3)                        #MUESTRAS LOS PRIMEROS 5 REGISTROS DEL DATAFRAME - df.tail()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped

## 🗺️__COMENCEMOS A EXPLORAR__📚
---

In [4]:
#HACEMOS UNA COPIA PROFUNDA.
df_work = df_raw.copy(deep = True)

In [5]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,Delivered

## 🧹 __LIMPIEMOS Y ESTANDARICEMOS UN "POCO" 🫧🧺__
---

In [6]:
#REVISEMOS LAS COLUMNAS CATEGÓRICAS BUSCANDO ESTANDARIZAR.

In [7]:
#MANEJO DE VALORES NULOS.

In [23]:
#DUPLICADOS
df_work[df_work.duplicated(keep = False)].sort_values(by ='customer_id', ascending = False).head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
67474,95174639-d54c-4d9b-9390-a695a25e5130,2024-03-08,400996,Benjamín García,benjamín.garcía_400996@example.com,Colombia,COL,Cartagena,1344 Calle Sur,P008,Office Chair,Furniture,3,200.0,45.0,72.50,600.0,30.0,108.30,750.80,Debit Card,Delivered
2000982,95174639-d54c-4d9b-9390-a695a25e5130,2024-03-08,400996,Benjamín García,benjamín.garcía_400996@example.com,Colombia,COL,Cartagena,1344 Calle Sur,P008,Office Chair,Furniture,3,200.0,45.0,72.50,600.0,30.0,108.30,750.80,Debit Card,Delivered
2000462,9e0ec4b1-787e-4e3c-8230-82e50e23a50f,2024-09-08,400960,Valentina Torres,valentina.torres_400960@example.com,Argentina,ARG,Mar del Plata,6077 Calle Este,P019,Sneakers,Fashion,1,85.0,0.7,6.05,85.0,0.0,16.15,107.20,Debit Card,Shipped
216121,9e0ec4b1-787e-4e3c-8230-82e50e23a50f,2024-09-08,400960,Valentina Torres,valentina.torres_400960@example.com,Argentina,ARG,Mar del Plata,6077 Calle Este,P019,Sneakers,Fashion,1,85.0,0.7,6.05,85.0,0.0,16.15,107.20,Debit Card,Shipped
1649636,5fe7105f-5dc4-4740-bcc4-0c66724f5413,2024-06-12,400907,Isabel Muñoz,isabel.muñoz_400907@example.com,México,MEX,Monterrey,3412 Calle Oeste,P014,Microwave Oven,Home,1,150.0,10.0,20.00,150.0,15.0,25.65,180.65,Debit Card,Processing

In [24]:
df_work.drop_duplicates(inplace = True)

/tmp/ipykernel_24738/3962262628.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work.drop_duplicates(inplace = True)

In [25]:
df_work[df_work.duplicated(keep = False)].sort_values(by ='customer_id', ascending = False).head()

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_name, customer_email, customer_country, country_code, customer_city, customer_address, product_id, product_name, product_category, quantity, price_per_unit, total_weight, shipping_cost, total_amount_gross, discount_amount, tax_amount, final_total_amount, payment_method, shipping_status]
Index: []

In [34]:
df_work['order_date'] = pd.to_datetime(df_work['order_date'], format = '%Y-%m-%d')

/tmp/ipykernel_24738/1436791924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['order_date'] = pd.to_datetime(df_work['order_date'], format = '%Y-%m-%d')

In [33]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,Delivered

In [8]:
#VERIFICAR INCONSISTENCIAS?

In [9]:
#GUARDAR DATA LIMPIA.

In [10]:
#BONUS EXTRA: GENERAR LISTAS DETECTANDO AUTOMÁTICA EL TIPO DE DATO CON EL MÉTODO select_dtypes()
cols_numericas   = df_work.select_dtypes(include=['number']).columns.tolist()
cols_categoricas = df_work.select_dtypes(include=['object']).columns.tolist()

In [11]:
df_work[cols_categoricas].head()

,order_id,order_date,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,Bank Transfer,Delivered

In [12]:
#VEAMOS LAS LISTAS CON LOS NOMBRES DE COLUMNAS DE CADA TIPO: ESTO ES ÚTIL PARA DARLE EL TRATAMIENTO CORRESPONDIENTE A CADA TIPO DE DATO.
print(f"- Columnas numéricas   : {cols_numericas}")
print(f"- Columnas categóricas : {cols_categoricas}")

- Columnas numéricas   : ['customer_id', 'quantity', 'price_per_unit', 'total_weight', 'shipping_cost', 'total_amount_gross', 'discount_amount', 'tax_amount', 'final_total_amount']
- Columnas categóricas : ['order_id', 'order_date', 'customer_name', 'customer_email', 'customer_country', 'country_code', 'customer_city', 'customer_address', 'product_id', 'product_name', 'product_category', 'payment_method', 'shipping_status']

## 🚩 __CLASIFICACIÓN DE VALORES NULOS <code>NaN</code>__ 👽
---

* __MCAR (MISSING COMPLETLY AT RANDOM):__ Cada registro que es nulo lo hace sin nungún patron específico. Es decir, cualquiera de los registros tiene la misma chance de estar vacío. RECOMENDACIÓN: ELIMINAR O IMPUTAR (MEDIA O LA MEDIANA)

* __MAR (MISSING AT RANDOM):__ Hay valores nulos, pero estos se relacionan con otra columna específica. EJ: Hay valores nulos, pero estos se asocian a una o varias columnas.

* __MNAR (MISSING AT NO RANDOM):__ El valor no está o aparece nulo, pero no es al azar. Por ejemplo: Persona de áreas ricas de la ciudad, no dan su nombre por privacidad, por lo que la coluna user_name, suele tener nulos.

In [13]:
df_work['shipping_status'].isna().groupby(df_work['customer_country']).mean().sort_values(ascending = False)

customer_country
Colombia     0.100464
México       0.100453
Chile        0.099923
Brasil       0.099819
Uruguay      0.099718
Argentina    0.099698
Ecuador      0.099649
Perú         0.099516
Name: shipping_status, dtype: float64

In [14]:
df_work['order_date'] = df_work['order_date'].astype('datetime64[ns]')

In [15]:
df_work = df_raw.dropna(subset = ['shipping_status'])

In [16]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,Delivered

## __♻️ Funciones en Python 🚀__

Las funciones son una metedología de generación de un esquema general de un proceso repetitivo en python. Se caracateriza al igual que cualquier función por tener entrada - proceso - salida.